{{/*
Exportarr Secret template for Radarr
Creates a Kubernetes Secret resource containing API keys for Exportarr metrics collection,
providing secure access credentials for monitoring and metrics export functionality.
*/}}
{{- if and .Values.exportarr.enabled .Values.exportarr.apiKeySecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.exportarr.apiKeySecret.name | default (printf "%s-exportarr" (include "radarr.fullname" .)) }}
  labels:
    {{- include "radarr.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.exportarr.apiKeySecret.key }}: {{ .Values.exportarr.apiKeySecret.value | b64enc }}
{{- end }}