{{/*
Ingress template for Tautulli
Creates a Kubernetes Ingress resource that provides external HTTP/HTTPS access to the Tautulli service,
including routing rules, TLS configuration, and host-based routing.
*/}}
{{- if .Values.tautulli.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "tautulli.fullname" . }}
  labels:
    {{- include "tautulli.labels" . | nindent 4 }}
  {{- with .Values.tautulli.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.tautulli.ingress.className }}
  ingressClassName: {{ .Values.tautulli.ingress.className }}
  {{- end }}
  {{- if .Values.tautulli.ingress.tls }}
  tls:
    {{- range .Values.tautulli.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.tautulli.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if .pathType }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              service:
                name: {{ include "tautulli.fullname" $ }}
                port:
                  number: {{ $.Values.tautulli.service.port }}
          {{- end }}
    {{- end }}
{{- end }}