{{/*
Secret template for Tautulli
Creates Kubernetes Secret resources containing sensitive configuration data,
including Plex tokens, API keys, and other confidential settings for the application.
*/}}
{{- if .Values.tautulli.plex.token }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tautulli.fullname" . }}-plex
  labels:
    {{- include "tautulli.labels" . | nindent 4 }}
    component: plex
type: Opaque
data:
  token: {{ .Values.tautulli.plex.token | b64enc | quote }}
{{- end }}