# Default values for sabnzbd
# This is a YAML-formatted file.

# Global settings
global:
  # -- Set the global timezone
  timezone: "Europe/London"

# SABnzbd configuration
sabnzbd:
  # -- Enable or disable SABnzbd
  enabled: true
  
  image:
    # -- SABnzbd image repository
    repository: lscr.io/linuxserver/sabnzbd
    # -- SABnzbd image tag
    tag: "latest"
    # -- Image pull policy
    pullPolicy: IfNotPresent

  # -- Environment variables for SABnzbd
  env:
    # -- Process User ID
    PUID: 1000
    # -- Process Group ID  
    PGID: 1000
    # -- Timezone
    TZ: "Europe/London"
    # -- Host for SABnzbd to bind to
    HOST: "0.0.0.0"
    # -- Port for SABnzbd web interface
    PORT: "8080"

  # Service configuration
  service:
    # -- Service type
    type: ClusterIP
    # -- Service port for web interface
    port: 8080
    # -- Target port on the pod
    targetPort: 8080
    # -- Additional service ports
    additionalPorts:
      # -- HTTPS port
      - name: https
        port: 9090
        targetPort: 9090
        protocol: TCP

  # Ingress configuration
  ingress:
    # -- Enable ingress
    enabled: false
    # -- Ingress class name
    className: ""
    # -- Ingress annotations
    annotations: {}
    # -- Ingress hosts configuration
    hosts:
      - host: sabnzbd.local
        paths:
          - path: /
            pathType: Prefix
    # -- TLS configuration
    tls: []

  # Persistence configuration
  persistence:
    # Configuration persistence
    config:
      # -- Enable config persistence
      enabled: true
      # -- Storage class for config volume
      storageClass: ""
      # -- Access mode for config volume
      accessMode: ReadWriteOnce
      # -- Size of config volume
      size: 2Gi
      # -- Mount path for config
      mountPath: /config
      # -- Existing claim name (optional)
      existingClaim: ""
      # NFS configuration
      nfs:
        # -- Enable NFS for config storage
        enabled: false
        # -- NFS server address
        server: ""
        # -- NFS export path
        path: ""
        # -- NFS mount options
        mountOptions:
          - nfsvers=4.1
          - hard
          - intr

    # Downloads persistence (completed downloads)
    downloads:
      # -- Enable downloads persistence
      enabled: true
      # -- Storage class for downloads volume
      storageClass: ""
      # -- Access mode for downloads volume
      accessMode: ReadWriteOnce
      # -- Size of downloads volume
      size: 100Gi
      # -- Mount path for downloads
      mountPath: /downloads
      # -- Existing claim name (optional)
      existingClaim: ""
      # NFS configuration
      nfs:
        # -- Enable NFS for downloads storage
        enabled: false
        # -- NFS server address
        server: ""
        # -- NFS export path
        path: ""
        # -- NFS mount options
        mountOptions:
          - nfsvers=4.1
          - hard
          - intr

    # Incomplete downloads persistence (active downloads)
    incomplete:
      # -- Enable incomplete downloads persistence
      enabled: true
      # -- Storage class for incomplete downloads volume
      storageClass: ""
      # -- Access mode for incomplete downloads volume
      accessMode: ReadWriteOnce
      # -- Size of incomplete downloads volume
      size: 100Gi
      # -- Mount path for incomplete downloads
      mountPath: /incomplete-downloads
      # -- Existing claim name (optional)
      existingClaim: ""
      # NFS configuration
      nfs:
        # -- Enable NFS for incomplete downloads storage
        enabled: false
        # -- NFS server address
        server: ""
        # -- NFS export path
        path: ""
        # -- NFS mount options
        mountOptions:
          - nfsvers=4.1
          - hard
          - intr

    # TV shows persistence
    tv:
      # -- Enable TV persistence
      enabled: true
      # -- Storage class for TV volume
      storageClass: ""
      # -- Access mode for TV volume
      accessMode: ReadWriteOnce
      # -- Size of TV volume
      size: 500Gi
      # -- Mount path for TV shows
      mountPath: /tv

    # Anime persistence
    anime:
      # -- Enable anime persistence
      enabled: true
      # -- Storage class for anime volume
      storageClass: ""
      # -- Access mode for anime volume
      accessMode: ReadWriteOnce
      # -- Size of anime volume
      size: 200Gi
      # -- Mount path for anime
      mountPath: /anime

    # Data persistence (shared with *arr apps)
    data:
      # -- Enable data persistence
      enabled: true
      # -- Storage class for data volume
      storageClass: ""
      # -- Access mode for data volume
      accessMode: ReadWriteOnce
      # -- Size of data volume
      size: 100Gi
      # -- Mount path for data
      mountPath: /data

  # Health checks
  healthcheck:
    # -- Enable health checks
    enabled: true
    # -- Liveness probe configuration
    livenessProbe:
      httpGet:
        path: /api/v1/status
        port: 8080
      initialDelaySeconds: 60
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 5
    # -- Readiness probe configuration
    readinessProbe:
      httpGet:
        path: /api/v1/status
        port: 8080
      initialDelaySeconds: 30
      periodSeconds: 15
      timeoutSeconds: 5
      failureThreshold: 3

  # Resource limits and requests
  resources:
    limits:
      cpu: 2000m
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 512Mi

  # Security context
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false

  # ConfigMap for additional configuration
  configMap:
    # -- Enable configMap creation
    enabled: false
    # -- Additional configuration data
    data: {}
    # -- Custom scripts
    scripts: {}

  # Homepage integration labels
  homepage:
    # -- Enable homepage integration
    enabled: true
    # -- Homepage group
    group: "Media"
    # -- Homepage name
    name: "SABnzbd"
    # -- Homepage description
    description: "Usenet Download Client"
    # -- Homepage widget type
    widget:
      type: "sabnzbd"
      # -- Internal URL for widget API calls
      url: "http://sabnzbd:8080"
      # -- API key for widget (set this in your deployment)
      key: ""

# Exportarr metrics exporter configuration
exportarr:
  # -- Enable Exportarr metrics exporter sidecar
  enabled: false
  
  image:
    # -- Exportarr image repository
    repository: ghcr.io/onedr0p/exportarr
    # -- Exportarr image tag
    tag: "v2.0"
    # -- Image pull policy
    pullPolicy: IfNotPresent

  # -- Command to run (application type)
  command: ["sabnzbd"]

  # -- Environment variables for Exportarr
  env:
    # -- Port for metrics endpoint
    PORT: "9707"
    # -- URL of SABnzbd instance
    URL: "http://localhost:8080"
    # -- API key for SABnzbd (should be set via secret)
    APIKEY: ""

  # Service configuration for metrics
  service:
    # -- Service type for metrics
    type: ClusterIP
    # -- Service port for metrics
    port: 9707
    # -- Service name for metrics
    name: metrics
    # -- Service annotations
    annotations: {}

  # ServiceMonitor configuration for Prometheus
  serviceMonitor:
    # -- Enable ServiceMonitor for Prometheus
    enabled: false
    # -- ServiceMonitor labels
    labels: {}
    # -- ServiceMonitor annotations
    annotations: {}
    # -- Scrape interval
    interval: "4m"
    # -- Scrape timeout
    scrapeTimeout: "90s"
    # -- Metrics path
    path: "/metrics"
    # -- Namespace selector
    namespaceSelector: {}
    # -- Target labels
    targetLabels: []
    # -- Metric relabeling configs
    metricRelabelings: []
    # -- Relabeling configs
    relabelings: []

  # Health checks
  healthcheck:
    # -- Enable health checks
    enabled: true
    # -- Liveness probe configuration
    livenessProbe:
      httpGet:
        path: /healthz
        port: 9707
      failureThreshold: 5
      periodSeconds: 10
      timeoutSeconds: 5
    # -- Readiness probe configuration
    readinessProbe:
      httpGet:
        path: /healthz
        port: 9707
      failureThreshold: 5
      periodSeconds: 10
      timeoutSeconds: 5

  # Resource limits and requests
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 64Mi

  # Security context
  securityContext:
    runAsUser: 65534
    runAsGroup: 65534
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL

  # API key secret configuration
  apiKeySecret:
    # -- Name of secret containing API key
    name: ""
    # -- Key within secret containing API key
    key: "api-key"
    # -- Create secret with API key (not recommended for production)
    create: false
    # -- API key value (only used if create is true)
    value: ""

# Gluetun VPN configuration
gluetun:
  # -- Enable Gluetun VPN sidecar
  enabled: false
  
  image:
    # -- Gluetun image repository
    repository: ghcr.io/qdm12/gluetun
    # -- Gluetun image tag
    tag: "latest"
    # -- Image pull policy
    pullPolicy: IfNotPresent

  # -- Security context for Gluetun (requires NET_ADMIN capability)
  securityContext:
    capabilities:
      add:
        - NET_ADMIN
    runAsUser: 0
    runAsGroup: 0

  # Sidecar configuration
  sidecar:
    # -- Run as sidecar container sharing network with SABnzbd
    enabled: true

  # Port forwarding configuration
  ports:
    # -- HTTP proxy port
    httpProxy: 8888
    # -- Shadowsocks TCP port  
    shadowsocksTcp: 8388
    # -- Shadowsocks UDP port
    shadowsocksUdp: 8388
    # -- Control server port
    control: 8000

  # Environment variables for VPN configuration
  env:
    # -- Timezone
    TZ: "Europe/London"
    # -- Enable HTTP proxy
    HTTPPROXY: "on"
    # -- Enable Shadowsocks
    SHADOWSOCKS: "on"
    # -- Firewall outbound subnets
    FIREWALL_OUTBOUND_SUBNETS: "192.168.0.0/16"
    # -- Enable VPN port forwarding
    VPN_PORT_FORWARDING: "on"
    # -- Server update period
    UPDATER_PERIOD: "24h"

  # VPN Provider configurations (uncomment and configure one)
  vpn:
    # NordVPN configuration
    nordvpn:
      # -- Enable NordVPN
      enabled: false
      # -- VPN service provider
      serviceProvider: "nordvpn"
      # -- VPN type
      type: "wireguard"
      # -- Wireguard private key (store in secret)
      privateKey: ""

    # Mullvad configuration  
    mullvad:
      # -- Enable Mullvad
      enabled: false
      # -- VPN service provider
      serviceProvider: "mullvad"
      # -- VPN type
      type: "wireguard"
      # -- Wireguard private key (store in secret)
      privateKey: ""
      # -- Wireguard addresses
      addresses: ""
      # -- Server cities
      serverCities: "London"

    # Private Internet Access configuration
    pia:
      # -- Enable Private Internet Access
      enabled: false
      # -- VPN service provider
      serviceProvider: "private internet access"
      # -- OpenVPN username (store in secret)
      username: ""
      # -- OpenVPN password (store in secret) 
      password: ""
      # -- Server regions
      serverRegions: "UK London"

  # Persistence for Gluetun
  persistence:
    # -- Enable persistence for Gluetun config
    enabled: true
    # -- Storage class
    storageClass: ""
    # -- Access mode
    accessMode: ReadWriteOnce
    # -- Volume size
    size: 1Gi
    # -- Mount path
    mountPath: /gluetun

  # Resource limits and requests
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Pod-level configuration  
pod:
  # -- Pod restart policy
  restartPolicy: Always
  # -- Pod security context
  securityContext:
    fsGroup: 1000
    fsGroupChangePolicy: "OnRootMismatch"
  # -- Node selector
  nodeSelector: {}
  # -- Tolerations
  tolerations: []
  # -- Affinity rules
  affinity: {}
  # -- Pod annotations
  annotations: {}
  # -- Pod labels
  labels: {}

# Service account configuration
serviceAccount:
  # -- Create service account
  create: true
  # -- Service account annotations
  annotations: {}
  # -- Service account name
  name: ""

# Network policies
networkPolicy:
  # -- Enable network policies
  enabled: false
  # -- Ingress rules for *arr applications
  ingress:
    # -- Allow traffic from Sonarr
    - from:
        - namespaceSelector:
            matchLabels:
              name: media
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: sonarr
      ports:
        - protocol: TCP
          port: 8080
    # -- Allow traffic from Radarr
    - from:
        - namespaceSelector:
            matchLabels:
              name: media
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: radarr
      ports:
        - protocol: TCP
          port: 8080
    # -- Allow traffic from Lidarr
    - from:
        - namespaceSelector:
            matchLabels:
              name: media
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: lidarr
      ports:
        - protocol: TCP
          port: 8080
  # -- Egress rules  
  egress:
    # -- Allow all egress when VPN is disabled
    - {}

# Pod Disruption Budget
podDisruptionBudget:
  # -- Enable PodDisruptionBudget
  enabled: false
  # -- Minimum number of pods that must be available
  minAvailable: 1
  # -- Maximum number of pods that can be unavailable
  maxUnavailable: ""

# Service Monitor for Prometheus
serviceMonitor:
  # -- Enable ServiceMonitor for Prometheus
  enabled: false
  # -- ServiceMonitor labels
  labels: {}
  # -- ServiceMonitor annotations
  annotations: {}
  # -- Scrape interval
  interval: "30s"
  # -- Scrape timeout
  scrapeTimeout: "10s"
  # -- Metrics path
  path: "/api/v1/stats"
  # -- Additional scrape parameters
  params: {}
  # -- Basic auth configuration
  basicAuth: {}
  # -- Bearer token secret
  bearerTokenSecret: {}
  # -- TLS configuration
  tlsConfig: {}
  # -- Relabeling configs
  relabelings: []
  # -- Metric relabeling configs
  metricRelabelings: []
  # -- Namespace selector
  namespaceSelector: {}
  # -- Target labels
  targetLabels: []

# Horizontal Pod Autoscaler
autoscaling:
  # -- Enable HPA
  enabled: false
  # -- Minimum number of replicas
  minReplicas: 1
  # -- Maximum number of replicas
  maxReplicas: 3
  # -- Target CPU utilization percentage
  targetCPUUtilizationPercentage: 80
  # -- Target memory utilization percentage
  targetMemoryUtilizationPercentage: 80