extends: default
rules:
  comments: enable
  empty-values: enable
  indentation:
    indent-sequences: consistent
    spaces: 2
  line-length: disable
  quoted-strings:
    quote-type: double
    required: only-when-needed
  truthy:
    allowed-values: [true, false, yes, no, on, off]
    check-keys: false
  document-start: disable
  key-duplicates: enable
  brackets:
    max-spaces-inside: 1
    min-spaces-inside: 0
  braces:
    max-spaces-inside: 1
    min-spaces-inside: 0
ignore: |
  incubator/*/templates/
  stable/*/templates/
  .github/
  **/*.schema.json
