{{/*
Secret template for Lidarr
Creates Kubernetes Secret resources containing sensitive configuration data,
including API keys, passwords, and other confidential settings for the application.
*/}}
{{- if .Values.gluetun.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lidarr.fullname" . }}-gluetun
  labels:
    {{- include "lidarr.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.gluetun.vpn.nordvpn.enabled }}
  wireguard-private-key: {{ .Values.gluetun.vpn.nordvpn.privateKey | b64enc | quote }}
  {{- else if .Values.gluetun.vpn.mullvad.enabled }}
  wireguard-private-key: {{ .Values.gluetun.vpn.mullvad.privateKey | b64enc | quote }}
  {{- else if .Values.gluetun.vpn.pia.enabled }}
  openvpn-username: {{ .Values.gluetun.vpn.pia.username | b64enc | quote }}
  openvpn-password: {{ .Values.gluetun.vpn.pia.password | b64enc | quote }}
  {{- end }}
{{- end }}