{{- if and .Values.exportarr.enabled .Values.exportarr.apiKeySecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.exportarr.apiKeySecret.name | default (printf "%s-exportarr" (include "lidarr.fullname" .)) }}
  labels:
    {{- include "lidarr.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.exportarr.apiKeySecret.key }}: {{ .Values.exportarr.apiKeySecret.value | b64enc }}
{{- end }}