{{/*
Ingress template for Gluetun
Creates a Kubernetes Ingress resource that provides external HTTP/HTTPS access to the Gluetun control interface,
including routing rules, TLS configuration, and host-based routing.
*/}}
{{- if .Values.gluetun.ingress.enabled -}}
{{- $fullName := include "gluetun.fullname" . -}}
{{- $svcPort := .Values.gluetun.service.internal.ports.control.port -}}
{{- if and .Values.gluetun.ingress.className (not (hasKey .Values.gluetun.ingress.annotations "kubernetes.io/ingress.class")) }}
  {{- $_ := set .Values.gluetun.ingress.annotations "kubernetes.io/ingress.class" .Values.gluetun.ingress.className}}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "gluetun.labels" . | nindent 4 }}
  {{- with .Values.gluetun.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.gluetun.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.gluetun.ingress.className }}
  {{- end }}
  {{- if .Values.gluetun.ingress.tls }}
  tls:
    {{- range .Values.gluetun.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.gluetun.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}