{{/*
PersistentVolumeClaim template for Gluetun
Creates Kubernetes PersistentVolumeClaim resources for data persistence,
defining storage requirements and access modes for the Gluetun VPN client.
*/}}
{{- if .Values.gluetun.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "gluetun.fullname" . }}-data
  labels:
    {{- include "gluetun.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.gluetun.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.gluetun.persistence.size }}
  {{- if .Values.gluetun.persistence.storageClass }}
  storageClassName: {{ .Values.gluetun.persistence.storageClass }}
  {{- end }}
{{- end }}