apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gluetun.fullname" . }}-vpn
  labels:
    {{- include "gluetun.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.gluetun.vpn.nordvpn.enabled }}
  wireguard-private-key: {{ .Values.gluetun.vpn.nordvpn.privateKey | b64enc | quote }}
  {{- else if .Values.gluetun.vpn.mullvad.enabled }}
  wireguard-private-key: {{ .Values.gluetun.vpn.mullvad.privateKey | b64enc | quote }}
  {{- else if .Values.gluetun.vpn.pia.enabled }}
  openvpn-username: {{ .Values.gluetun.vpn.pia.username | b64enc | quote }}
  openvpn-password: {{ .Values.gluetun.vpn.pia.password | b64enc | quote }}
  {{- else if .Values.gluetun.vpn.expressvpn.enabled }}
  openvpn-username: {{ .Values.gluetun.vpn.expressvpn.username | b64enc | quote }}
  openvpn-password: {{ .Values.gluetun.vpn.expressvpn.password | b64enc | quote }}
  {{- else if .Values.gluetun.vpn.surfshark.enabled }}
  openvpn-username: {{ .Values.gluetun.vpn.surfshark.username | b64enc | quote }}
  openvpn-password: {{ .Values.gluetun.vpn.surfshark.password | b64enc | quote }}
  {{- end }}