{{/*
ServiceAccount template for Gluetun
Creates a Kubernetes ServiceAccount resource that provides an identity for processes running in pods,
enabling fine-grained access control and security configurations for the VPN client.
*/}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gluetun.serviceAccountName" . }}
  labels:
    {{- include "gluetun.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}