{{/*
Ingress template for Pocket ID
Creates a Kubernetes Ingress resource that provides external HTTP/HTTPS access to the Pocket ID service,
including routing rules, TLS configuration, and host-based routing.
*/}}
{{- if .Values.ingress.enabled -}}
{{- $fullName := include "pocket-id.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-external
  labels:
{{ include "pocket-id.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
{{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
        {{- range .Values.ingress.paths }}
          - path: {{ .path }}
            backend:
              service:
                name: {{ $fullName }}-service
                port:
                  number: {{ $.Values.service.port }}
            pathType: {{ .pathType | default "ImplementationSpecific" }}
        {{- end }}
{{- end }}
