# Example values file for media-centre chart
# This shows a typical production configuration

# Global settings for the entire media stack
global:
  # Use fast SSD storage class for better performance
  storageClass: "fast-ssd"
  
  # Shared media storage configuration
  media:
    enabled: true
    size: 5Ti  # Large storage for complete media library
    storageClass: "bulk-storage"  # Use cheaper storage for media files
    accessMode: ReadWriteMany
    
  # Shared downloads storage
  downloads:
    enabled: true
    size: 1Ti  # Sufficient for active downloads
    storageClass: "fast-ssd"  # Fast storage for download performance
    accessMode: ReadWriteMany
    
  # Network configuration
  network:
    useVPN: true
    vpnProvider: "nordvpn"

# VPN Configuration - Required for secure downloading
gluetun:
  enabled: true
  image:
    repository: qmcgaw/gluetun
    tag: "v3.37.0"  # Use specific version for stability
  env:
    VPN_SERVICE_PROVIDER: "nordvpn"
    VPN_TYPE: "openvpn"
    # These should be set via secrets in production:
    # OPENVPN_USER: "your-vpn-username"
    # OPENVPN_PASSWORD: "your-vpn-password"
    SERVER_COUNTRIES: "Netherlands,Germany"
    LOG_LEVEL: "info"
  service:
    main:
      type: ClusterIP
      ports:
        http:
          port: 8000
  persistence:
    config:
      enabled: true
      size: 1Gi
      storageClass: "fast-ssd"

# Usenet downloader
sabnzbd:
  enabled: true
  image:
    repository: lscr.io/linuxserver/sabnzbd
    tag: "4.1.0"
  env:
    TZ: "America/New_York"
    PUID: 1000
    PGID: 1000
  service:
    main:
      type: ClusterIP
      ports:
        http:
          port: 8080
  persistence:
    config:
      enabled: true
      size: 5Gi
      storageClass: "fast-ssd"
    downloads:
      enabled: true
      existingClaim: "media-centre-downloads"  # Use shared downloads storage
      mountPath: /downloads
    incomplete-downloads:
      enabled: true
      size: 100Gi
      storageClass: "fast-ssd"
      mountPath: /incomplete-downloads
  # Route through VPN
  podAnnotations:
    k8s.v1.cni.cncf.io/networks: "gluetun"

# Torrent downloader
qbittorrent:
  enabled: true
  image:
    repository: lscr.io/linuxserver/qbittorrent
    tag: "4.6.0"
  env:
    TZ: "America/New_York"
    PUID: 1000
    PGID: 1000
    WEBUI_PORT: 8080
  service:
    main:
      type: ClusterIP
      ports:
        http:
          port: 8080
    bittorrent:
      enabled: true
      type: ClusterIP
      ports:
        bittorrent:
          port: 6881
          protocol: TCP
  persistence:
    config:
      enabled: true
      size: 5Gi
      storageClass: "fast-ssd"
    downloads:
      enabled: true
      existingClaim: "media-centre-downloads"  # Use shared downloads storage
      mountPath: /downloads
  # Route through VPN
  podAnnotations:
    k8s.v1.cni.cncf.io/networks: "gluetun"

# Indexer manager - Essential for automation
prowlarr:
  enabled: true
  image:
    repository: lscr.io/linuxserver/prowlarr
    tag: "1.10.5"
  env:
    TZ: "America/New_York"
    PUID: 1000
    PGID: 1000
  service:
    main:
      type: ClusterIP
      ports:
        http:
          port: 9696
  persistence:
    config:
      enabled: true
      size: 2Gi
      storageClass: "fast-ssd"
  exportarr:
    enabled: true
    image:
      repository: onedr0p/exportarr
      tag: "v1.5.3"
    port: 9707

# TV show management
sonarr:
  enabled: true
  image:
    repository: lscr.io/linuxserver/sonarr
    tag: "4.0.0"
  env:
    TZ: "America/New_York"
    PUID: 1000
    PGID: 1000
  service:
    main:
      type: LoadBalancer  # Expose externally for easy access
      ports:
        http:
          port: 8989
  persistence:
    config:
      enabled: true
      size: 10Gi  # Larger config for extensive TV library
      storageClass: "fast-ssd"
    media:
      enabled: true
      existingClaim: "media-centre-media"  # Use shared media storage
      mountPath: /tv
  exportarr:
    enabled: true
    image:
      repository: onedr0p/exportarr
      tag: "v1.5.3"
    port: 9707

# Movie management
radarr:
  enabled: true
  image:
    repository: lscr.io/linuxserver/radarr
    tag: "5.1.3"
  env:
    TZ: "America/New_York"
    PUID: 1000
    PGID: 1000
  service:
    main:
      type: LoadBalancer  # Expose externally for easy access
      ports:
        http:
          port: 7878
  persistence:
    config:
      enabled: true
      size: 10Gi  # Larger config for extensive movie library
      storageClass: "fast-ssd"
    media:
      enabled: true
      existingClaim: "media-centre-media"  # Use shared media storage
      mountPath: /movies
  exportarr:
    enabled: true
    image:
      repository: onedr0p/exportarr
      tag: "v1.5.3"
    port: 9707

# Music management
lidarr:
  enabled: true
  image:
    repository: lscr.io/linuxserver/lidarr
    tag: "2.0.7"
  env:
    TZ: "America/New_York"
    PUID: 1000
    PGID: 1000
  service:
    main:
      type: ClusterIP
      ports:
        http:
          port: 8686
  persistence:
    config:
      enabled: true
      size: 5Gi
      storageClass: "fast-ssd"
    media:
      enabled: true
      existingClaim: "media-centre-media"  # Use shared media storage
      mountPath: /music
  exportarr:
    enabled: true
    image:
      repository: onedr0p/exportarr
      tag: "v1.5.3"
    port: 9707

# Book management - Disabled by default as not everyone needs it
readarr:
  enabled: false
  image:
    repository: lscr.io/linuxserver/readarr
    tag: "0.3.10"
  env:
    TZ: "America/New_York"
    PUID: 1000
    PGID: 1000
  service:
    main:
      type: ClusterIP
      ports:
        http:
          port: 8787
  persistence:
    config:
      enabled: true
      size: 2Gi
      storageClass: "fast-ssd"
    media:
      enabled: true
      size: 200Gi  # Smaller dedicated storage for books
      storageClass: "bulk-storage"
      mountPath: /books
  exportarr:
    enabled: true
    image:
      repository: onedr0p/exportarr
      tag: "v1.5.3"
    port: 9707

# Subtitle management
bazarr:
  enabled: true
  image:
    repository: lscr.io/linuxserver/bazarr
    tag: "1.4.0"
  env:
    TZ: "America/New_York"
    PUID: 1000
    PGID: 1000
  service:
    main:
      type: ClusterIP
      ports:
        http:
          port: 6767
  persistence:
    config:
      enabled: true
      size: 2Gi
      storageClass: "fast-ssd"
    media:
      enabled: true
      existingClaim: "media-centre-media"  # Use shared media storage for subtitle access
      mountPath: /media
  exportarr:
    enabled: true
    image:
      repository: onedr0p/exportarr
      tag: "v1.5.3"
    port: 9707