{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "pocket-id.fullname" . }}
  labels:
    {{- include "pocket-id.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pocket-id.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        {{- if .Values.networkPolicy.ingress.from }}
        {{- toYaml .Values.networkPolicy.ingress.from | nindent 8 }}
        {{- else }}
        # Allow traffic from pods with matching labels
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "pocket-id.name" . }}
        # Allow traffic from ingress controller namespace
        {{- if .Values.networkPolicy.ingressControllerNamespace }}
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.networkPolicy.ingressControllerNamespace }}
        {{- end }}
        {{- end }}
      ports:
        - protocol: TCP
          port: 1411
  egress:
    # Allow DNS resolution
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
    # Allow outbound HTTPS traffic (for OAuth providers, etc.)
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 169.254.169.254/32  # AWS metadata service
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80
{{- end }}