kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "pocket-id.fullname" . }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  storageClassName: {{ .Values.storage.storageClassName }}