{{/*
ConfigMap template for SABnzbd
Creates a Kubernetes ConfigMap resource containing configuration data,
providing non-sensitive configuration settings and environment variables for the application.
*/}}
{{- if .Values.sabnzbd.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sabnzbd.fullname" . }}-config
  labels:
    {{- include "sabnzbd.labels" . | nindent 4 }}
data:
  {{- with .Values.sabnzbd.configMap.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- with .Values.sabnzbd.configMap.scripts }}
  {{- range $name, $content := . }}
  {{ $name }}: |
    {{- $content | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}