{{/*
Deployment template for SABnzbd
Creates a Kubernetes Deployment resource that manages the SABnzbd application pods,
including container configuration, environment variables, volume mounts, and resource limits.
*/}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sabnzbd.fullname" . }}
  labels:
    {{- include "sabnzbd.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "sabnzbd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.sabnzbd.configMap.enabled }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.sabnzbd.homepage.enabled }}
        homepage.group: {{ .Values.sabnzbd.homepage.group | quote }}
        homepage.name: {{ .Values.sabnzbd.homepage.name | quote }}
        homepage.description: {{ .Values.sabnzbd.homepage.description | quote }}
        homepage.href: http://{{ include "sabnzbd.fullname" . }}:{{ .Values.sabnzbd.service.port }}
        homepage.widget.type: {{ .Values.sabnzbd.homepage.widget.type | quote }}
        homepage.widget.url: {{ .Values.sabnzbd.homepage.widget.url | quote }}
        {{- if .Values.sabnzbd.homepage.widget.key }}
        homepage.widget.key: {{ .Values.sabnzbd.homepage.widget.key | quote }}
        {{- end }}
        {{- end }}
        {{- with .Values.pod.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "sabnzbd.selectorLabels" . | nindent 8 }}
        {{- with .Values.pod.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "sabnzbd.serviceAccountName" . }}
      {{- end }}
      restartPolicy: {{ .Values.pod.restartPolicy }}
      securityContext:
        {{- toYaml .Values.pod.securityContext | nindent 8 }}
      {{- if .Values.gluetun.enabled }}
      initContainers:
        - name: wait-for-vpn
          image: busybox:1.35
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for VPN connection to be established..."
              until wget -q --timeout=5 --tries=1 --spider http://checkip.amazonaws.com/ 2>/dev/null; do
                echo "VPN not ready, waiting 5 seconds..."
                sleep 5
              done
              echo "VPN connection established"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
      {{- end }}
      containers:
        {{- if .Values.gluetun.enabled }}
        - name: gluetun
          image: "{{ .Values.gluetun.image.repository }}:{{ .Values.gluetun.image.tag }}"
          imagePullPolicy: {{ .Values.gluetun.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.gluetun.securityContext | nindent 12 }}
          env:
            - name: TZ
              value: {{ .Values.gluetun.env.TZ | quote }}
            - name: HTTPPROXY
              value: {{ .Values.gluetun.env.HTTPPROXY | quote }}
            - name: SHADOWSOCKS
              value: {{ .Values.gluetun.env.SHADOWSOCKS | quote }}
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: {{ .Values.gluetun.env.FIREWALL_OUTBOUND_SUBNETS | quote }}
            - name: VPN_PORT_FORWARDING
              value: {{ .Values.gluetun.env.VPN_PORT_FORWARDING | quote }}
            - name: UPDATER_PERIOD
              value: {{ .Values.gluetun.env.UPDATER_PERIOD | quote }}
            {{- if .Values.gluetun.vpn.nordvpn.enabled }}
            - name: VPN_SERVICE_PROVIDER
              value: {{ .Values.gluetun.vpn.nordvpn.serviceProvider | quote }}
            - name: VPN_TYPE
              value: {{ .Values.gluetun.vpn.nordvpn.type | quote }}
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "sabnzbd.fullname" . }}-vpn
                  key: wireguard-private-key
            {{- else if .Values.gluetun.vpn.mullvad.enabled }}
            - name: VPN_SERVICE_PROVIDER
              value: {{ .Values.gluetun.vpn.mullvad.serviceProvider | quote }}
            - name: VPN_TYPE
              value: {{ .Values.gluetun.vpn.mullvad.type | quote }}
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "sabnzbd.fullname" . }}-vpn
                  key: wireguard-private-key
            {{- if .Values.gluetun.vpn.mullvad.addresses }}
            - name: WIREGUARD_ADDRESSES
              value: {{ .Values.gluetun.vpn.mullvad.addresses | quote }}
            {{- end }}
            {{- if .Values.gluetun.vpn.mullvad.serverCities }}
            - name: SERVER_CITIES
              value: {{ .Values.gluetun.vpn.mullvad.serverCities | quote }}
            {{- end }}
            {{- else if .Values.gluetun.vpn.pia.enabled }}
            - name: VPN_SERVICE_PROVIDER
              value: {{ .Values.gluetun.vpn.pia.serviceProvider | quote }}
            - name: OPENVPN_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "sabnzbd.fullname" . }}-vpn
                  key: openvpn-username
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "sabnzbd.fullname" . }}-vpn
                  key: openvpn-password
            - name: SERVER_REGIONS
              value: {{ .Values.gluetun.vpn.pia.serverRegions | quote }}
            {{- end }}
          ports:
            - name: http-proxy
              containerPort: {{ .Values.gluetun.ports.httpProxy }}
              protocol: TCP
            - name: shadowsocks-tcp
              containerPort: {{ .Values.gluetun.ports.shadowsocksTcp }}
              protocol: TCP
            - name: shadowsocks-udp
              containerPort: {{ .Values.gluetun.ports.shadowsocksUdp }}
              protocol: UDP
            - name: control
              containerPort: {{ .Values.gluetun.ports.control }}
              protocol: TCP
          volumeMounts:
            {{- if .Values.gluetun.persistence.enabled }}
            - name: gluetun-config
              mountPath: {{ .Values.gluetun.persistence.mountPath }}
            {{- end }}
          resources:
            {{- toYaml .Values.gluetun.resources | nindent 12 }}
        {{- end }}
        - name: sabnzbd
          image: "{{ .Values.sabnzbd.image.repository }}:{{ .Values.sabnzbd.image.tag }}"
          imagePullPolicy: {{ .Values.sabnzbd.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.sabnzbd.securityContext | nindent 12 }}
          env:
            {{- range $key, $value := .Values.sabnzbd.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.sabnzbd.service.targetPort }}
              protocol: TCP
            {{- range .Values.sabnzbd.service.additionalPorts }}
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
              protocol: {{ .protocol }}
            {{- end }}
          {{- if .Values.sabnzbd.healthcheck.enabled }}
          livenessProbe:
            {{- toYaml .Values.sabnzbd.healthcheck.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.sabnzbd.healthcheck.readinessProbe | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.sabnzbd.persistence.config.enabled }}
            - name: config
              mountPath: {{ .Values.sabnzbd.persistence.config.mountPath }}
            {{- end }}
            {{- if .Values.sabnzbd.persistence.downloads.enabled }}
            - name: downloads
              mountPath: {{ .Values.sabnzbd.persistence.downloads.mountPath }}
            {{- end }}
            {{- if .Values.sabnzbd.persistence.incomplete.enabled }}
            - name: incomplete
              mountPath: {{ .Values.sabnzbd.persistence.incomplete.mountPath }}
            {{- end }}
            {{- if .Values.sabnzbd.persistence.tv.enabled }}
            - name: tv
              mountPath: {{ .Values.sabnzbd.persistence.tv.mountPath }}
            {{- end }}
            {{- if .Values.sabnzbd.persistence.anime.enabled }}
            - name: anime
              mountPath: {{ .Values.sabnzbd.persistence.anime.mountPath }}
            {{- end }}
            {{- if .Values.sabnzbd.persistence.data.enabled }}
            - name: data
              mountPath: {{ .Values.sabnzbd.persistence.data.mountPath }}
            {{- end }}
            {{- if .Values.sabnzbd.configMap.enabled }}
            - name: config-files
              mountPath: /config-files
              readOnly: true
            {{- end }}
          resources:
            {{- toYaml .Values.sabnzbd.resources | nindent 12 }}
        {{- if .Values.exportarr.enabled }}
        - name: exportarr
          image: "{{ .Values.exportarr.image.repository }}:{{ .Values.exportarr.image.tag }}"
          imagePullPolicy: {{ .Values.exportarr.image.pullPolicy }}
          command: {{ .Values.exportarr.command | toJson }}
          env:
            - name: PORT
              value: {{ .Values.exportarr.env.PORT | quote }}
            - name: URL
              value: {{ .Values.exportarr.env.URL | quote }}
            - name: APIKEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.exportarr.apiKeySecret.name | default (printf "%s-exportarr" (include "sabnzbd.fullname" .)) }}
                  key: {{ .Values.exportarr.apiKeySecret.key }}
          ports:
            - name: metrics
              containerPort: {{ .Values.exportarr.env.PORT }}
              protocol: TCP
          {{- if .Values.exportarr.healthcheck.enabled }}
          livenessProbe:
            {{- toYaml .Values.exportarr.healthcheck.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.exportarr.healthcheck.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.exportarr.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.exportarr.securityContext | nindent 12 }}
        {{- end }}
      volumes:
        {{- if .Values.sabnzbd.persistence.config.enabled }}
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "sabnzbd.fullname" . }}-config
        {{- end }}
        {{- if .Values.sabnzbd.persistence.downloads.enabled }}
        - name: downloads
          persistentVolumeClaim:
            claimName: {{ include "sabnzbd.fullname" . }}-downloads
        {{- end }}
        {{- if .Values.sabnzbd.persistence.incomplete.enabled }}
        - name: incomplete
          persistentVolumeClaim:
            claimName: {{ include "sabnzbd.fullname" . }}-incomplete
        {{- end }}
        {{- if .Values.sabnzbd.persistence.tv.enabled }}
        - name: tv
          persistentVolumeClaim:
            claimName: {{ include "sabnzbd.fullname" . }}-tv
        {{- end }}
        {{- if .Values.sabnzbd.persistence.anime.enabled }}
        - name: anime
          persistentVolumeClaim:
            claimName: {{ include "sabnzbd.fullname" . }}-anime
        {{- end }}
        {{- if .Values.sabnzbd.persistence.data.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "sabnzbd.fullname" . }}-data
        {{- end }}
        {{- if and .Values.gluetun.enabled .Values.gluetun.persistence.enabled }}
        - name: gluetun-config
          persistentVolumeClaim:
            claimName: {{ include "sabnzbd.fullname" . }}-gluetun
        {{- end }}
        {{- if .Values.sabnzbd.configMap.enabled }}
        - name: config-files
          configMap:
            name: {{ include "sabnzbd.fullname" . }}-config
        {{- end }}
      {{- with .Values.pod.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pod.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pod.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}