{{/*
Create NFS PersistentVolumes for enabled volumes with NFS configuration
*/}}
{{- range $volumeName, $volume := .Values.sabnzbd.persistence }}
{{- if and $volume.enabled (not $volume.existingClaim) $volume.nfs.enabled }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "sabnzbd.fullname" $ }}-{{ $volumeName }}-nfs
  labels:
    {{- include "sabnzbd.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $volumeName }}
    app.kubernetes.io/volume-type: {{ $volumeName }}
    storage.kubernetes.io/type: nfs
spec:
  capacity:
    storage: {{ $volume.size }}
  accessModes:
    - {{ $volume.accessMode }}
  nfs:
    server: {{ $volume.nfs.server }}
    path: {{ $volume.nfs.path }}
  {{- if $volume.nfs.mountOptions }}
  mountOptions:
    {{- toYaml $volume.nfs.mountOptions | nindent 4 }}
  {{- end }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
{{- end }}
{{- end }}

{{/*
Create PersistentVolumeClaims for all enabled volumes
*/}}
{{- range $volumeName, $volume := .Values.sabnzbd.persistence }}
{{- if and $volume.enabled (not $volume.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sabnzbd.fullname" $ }}-{{ $volumeName }}
  labels:
    {{- include "sabnzbd.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $volumeName }}
    app.kubernetes.io/volume-type: {{ $volumeName }}
    {{- if $volume.nfs.enabled }}
    storage.kubernetes.io/type: nfs
    {{- end }}
spec:
  accessModes:
    - {{ $volume.accessMode }}
  resources:
    requests:
      storage: {{ $volume.size }}
  {{- if $volume.nfs.enabled }}
  volumeName: {{ include "sabnzbd.fullname" $ }}-{{ $volumeName }}-nfs
  storageClassName: ""
  {{- else if $volume.storageClass }}
  storageClassName: {{ $volume.storageClass }}
  {{- end }}
{{- end }}
{{- end }}