{{- if .Values.gluetun.enabled }}
{{- if or .Values.gluetun.vpn.nordvpn.enabled .Values.gluetun.vpn.mullvad.enabled .Values.gluetun.vpn.pia.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sabnzbd.fullname" . }}-vpn
  labels:
    {{- include "sabnzbd.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.gluetun.vpn.nordvpn.enabled }}
  {{- if .Values.gluetun.vpn.nordvpn.privateKey }}
  wireguard-private-key: {{ .Values.gluetun.vpn.nordvpn.privateKey | b64enc }}
  {{- end }}
  {{- else if .Values.gluetun.vpn.mullvad.enabled }}
  {{- if .Values.gluetun.vpn.mullvad.privateKey }}
  wireguard-private-key: {{ .Values.gluetun.vpn.mullvad.privateKey | b64enc }}
  {{- end }}
  {{- else if .Values.gluetun.vpn.pia.enabled }}
  {{- if .Values.gluetun.vpn.pia.username }}
  openvpn-username: {{ .Values.gluetun.vpn.pia.username | b64enc }}
  {{- end }}
  {{- if .Values.gluetun.vpn.pia.password }}
  openvpn-password: {{ .Values.gluetun.vpn.pia.password | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}