{{/*
Service template for Overseerr
Creates a Kubernetes Service resource that exposes the Overseerr application pods,
defining network access and load balancing for the application.
*/}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "overseerr.fullname" . }}
  labels:
    {{- include "overseerr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.overseerr.service.type }}
  ports:
    - port: {{ .Values.overseerr.service.port }}
      targetPort: {{ .Values.overseerr.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "overseerr.selectorLabels" . | nindent 4 }}