{{- if not .Values.cloudflareddns.credentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflareddns.fullname" . }}
  labels:
    {{- include "cloudflareddns.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.cloudflareddns.credentials.email }}
  cf-email: {{ .Values.cloudflareddns.credentials.email | b64enc | quote }}
  {{- else }}
  cf-email: {{ "" | b64enc | quote }}
  {{- end }}
  {{- if .Values.cloudflareddns.credentials.apiKey }}
  cf-apikey: {{ .Values.cloudflareddns.credentials.apiKey | b64enc | quote }}
  {{- else }}
  cf-apikey: {{ "" | b64enc | quote }}
  {{- end }}
  {{- if .Values.cloudflareddns.credentials.apiToken }}
  cf-apitoken: {{ .Values.cloudflareddns.credentials.apiToken | b64enc | quote }}
  {{- else }}
  cf-apitoken: {{ "" | b64enc | quote }}
  {{- end }}
  {{- if .Values.cloudflareddns.credentials.apiTokenZone }}
  cf-apitoken-zone: {{ .Values.cloudflareddns.credentials.apiTokenZone | b64enc | quote }}
  {{- else }}
  cf-apitoken-zone: {{ "" | b64enc | quote }}
  {{- end }}
{{- end }}