{{/*
ServiceAccount template for Bazarr
Creates a Kubernetes ServiceAccount resource that provides an identity for processes running in pods,
enabling fine-grained access control and security configurations for the application.
*/}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bazarr.serviceAccountName" . }}
  labels:
    {{- include "bazarr.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}