{{/*
Service template for Bazarr
Creates a Kubernetes Service resource that exposes the Bazarr application pods,
defining network access and load balancing for the application.
*/}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bazarr.fullname" . }}
  labels:
    {{- include "bazarr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.bazarr.service.type }}
  ports:
    - port: {{ .Values.bazarr.service.port }}
      targetPort: {{ .Values.bazarr.service.targetPort }}
      protocol: TCP
      name: http
    {{- if .Values.exportarr.enabled }}
    - port: {{ .Values.exportarr.service.port }}
      targetPort: {{ .Values.exportarr.env.PORT }}
      protocol: TCP
      name: {{ .Values.exportarr.service.name }}
    {{- end }}
  selector:
    {{- include "bazarr.selectorLabels" . | nindent 4 }}