remote: origin
target-branch: master
chart-dirs:
  - stable
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
  - stable=https://charts.helm.sh/stable
helm-extra-args: --timeout 600s
check-version-increment: true
validate-chart-schema: true
validate-yaml: true
debug: true
upgrade: true
helm-extra-set-args: "--set=replicaCount=1"
excluded-charts: []