name: Lint and Test Charts

on:
  pull_request:
    paths:
      - 'stable/**'
  workflow_dispatch:

env:
  HELM_VERSION: "3.13.2"
  CHART_TESTING_VERSION: "3.10.1"
  KUBECONFORM_VERSION: "0.6.4"
  HELM_DOCS_VERSION: "1.11.3"

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Cache Helm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/helm
          key: ${{ runner.os }}-helm-${{ hashFiles('**/Chart.yaml') }}
          restore-keys: |
            ${{ runner.os }}-helm-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Add Helm repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add stable https://charts.helm.sh/stable
          helm repo update

      - name: Run chart-testing (lint)
        run: ct lint --config .github/workflow-extras/ct.yaml

  lint-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache helm-docs
        uses: actions/cache@v3
        with:
          path: ./helm-docs
          key: helm-docs-${{ env.HELM_DOCS_VERSION }}

      - name: Run helm-docs
        run: .github/workflow-extras/helm-docs.sh

  security-scan:
    runs-on: ubuntu-latest
    needs: lint-chart
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: 'stable/'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

  validate-manifests:
    runs-on: ubuntu-latest
    needs: lint-chart
    strategy:
      matrix:
        k8s-version:
          - "1.26.0"
          - "1.27.0"
          - "1.28.0"
          - "1.29.0"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Cache kubeconform
        uses: actions/cache@v3
        with:
          path: ./kubeconform
          key: kubeconform-${{ env.KUBECONFORM_VERSION }}

      - name: Add Helm repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add stable https://charts.helm.sh/stable
          helm repo update

      - name: Validate Kubernetes manifests
        run: .github/workflow-extras/kubeconform.sh
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s-version }}

  install-chart:
    name: install-chart
    runs-on: ubuntu-latest
    needs: [lint-chart, lint-docs, validate-manifests]
    strategy:
      matrix:
        k8s:
          - v1.26.0
          - v1.27.0
          - v1.28.0
          - v1.29.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create kind cluster
        uses: helm/kind-action@v1.8.0
        with:
          node_image: kindest/node:${{ matrix.k8s }}
          kubectl_version: ${{ matrix.k8s }}

      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v2.6.1
        with:
          command: install
          config: .github/workflow-extras/ct.yaml