name: Update Dependencies

on:
  schedule:
    - cron: '0 2 * * 1' # Weekly on Monday at 2 AM
  workflow_dispatch:

env:
  HELM_VERSION: "3.13.2"

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Add Helm repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add stable https://charts.helm.sh/stable
          helm repo update

      - name: Update Helm dependencies
        run: |
          updated_charts=""
          find stable -name "Chart.yaml" -exec dirname {} \; | while read -r chart_dir; do
            echo "Checking dependencies for $chart_dir"
            if [[ -f "$chart_dir/Chart.lock" ]]; then
              echo "Updating dependencies for $chart_dir"
              helm dependency update "$chart_dir"
              if git diff --quiet "$chart_dir/Chart.lock"; then
                echo "No changes in $chart_dir"
              else
                echo "Dependencies updated in $chart_dir"
                updated_charts="$updated_charts\n- $chart_dir"
              fi
            else
              echo "No Chart.lock found in $chart_dir, skipping"
            fi
          done
          echo "UPDATED_CHARTS<<EOF" >> $GITHUB_ENV
          echo -e "$updated_charts" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet; then
            echo "No dependency updates found"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "Dependency updates found"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update Helm chart dependencies'
          title: 'chore: update Helm chart dependencies'
          body: |
            ## Automated Dependency Update
            
            This PR contains automated updates to Helm chart dependencies.
            
            ### Updated Charts
            ${{ env.UPDATED_CHARTS }}
            
            ### Changes
            - Updated Chart.lock files with latest dependency versions
            - Verified compatibility with current chart configurations
            
            Please review the changes before merging.
            
            ---
            *This PR was created automatically by the dependency update workflow*
          branch: dependency-updates
          delete-branch: true
          labels: |
            dependencies
            automated

      - name: No updates notification
        if: steps.changes.outputs.has_changes == 'false'
        run: echo "✅ All dependencies are up to date"