{{/*
Ingress template for Readarr
Creates a Kubernetes Ingress resource that provides external HTTP/HTTPS access to the Readarr service,
including routing rules, TLS configuration, and host-based routing.
*/}}
{{- if .Values.readarr.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "readarr.fullname" . }}
  labels:
    {{- include "readarr.labels" . | nindent 4 }}
  {{- with .Values.readarr.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.readarr.ingress.className }}
  ingressClassName: {{ .Values.readarr.ingress.className }}
  {{- end }}
  {{- if .Values.readarr.ingress.tls }}
  tls:
    {{- range .Values.readarr.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.readarr.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if .pathType }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              service:
                name: {{ include "readarr.fullname" $ }}
                port:
                  number: {{ $.Values.readarr.service.port }}
          {{- end }}
    {{- end }}
{{- end }}